language: php

php:
  - "5.4"
  - "5.3"


before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --configuration phpunit.xml --coverage-text



notifications:
  email: "andrey@kucherenko.org"